PCVL-246 customizable job name
Quandela/Perceval pull request #156
Opened 2022-12-13 09:20 UTC by ericbrts

Job names can be customized through algorithm or job instances.

1. An algorithm has a `default_job_name` field it uses to name the jobs it creates. If `default_job_name` is missing, it must generate a name on its own (sampler names the jobs with the primitive that has been called - probs, samples or sample_count).

2. Jobs have a name setter:
```python
job.name = "My job name!"
```

2022-12-13 12:36 UTC, Aubaert requested changes

2022-12-13 12:36 UTC, Aubaert commented on perceval/runtime/remote_job.py
> +            self._payload['payload'].update(kwargs)
It supposes that the payload has been created by a processor before (maybe add a docstring ?)

2022-12-14 16:15 UTC, mario-valdivia requested changes

2022-12-14 16:15 UTC, mario-valdivia commented on perceval/algorithm/analyzer.py
> +            job.name = self.default_job_name or f'analyzer ({idx+1}/{len(self.input_states_list)})'
def analyser.__init():
  self.default_name = "analyzer"

def analyzer.compute():
   job.name = f'{self.default_job_name} ({idx+1}/{len(self.input_states_list)})'

2022-12-15 09:00 UTC, Alex-PLACET commented
Can you squash the commits ?

2022-12-15 10:46 UTC, ericbrts commented on perceval/algorithm/sampler.py
> +            job_name = self.default_job_name if self.default_job_name is not None else method
The thing is, the command of a Sampler is not the correct one (i.e. the one the user asked for) whenever a post-conversion is needed. So I prefer setting `method` dynamically when the `default_job_name` was not set by the user.

2022-12-15 11:08 UTC, merged