PCVL-391 compose postselect
Quandela/Perceval pull request #245
Opened 2023-07-25 08:21 UTC by ericbrts

2023-07-25 10:36 UTC, MarionQuandela requested changes

2023-07-25 10:36 UTC, MarionQuandela commented on perceval/utils/postselect.py
> +        :return: A PostSelect with the permutation applied
👍

2023-07-26 09:42 UTC, ericbrts commented on perceval/components/abstract_processor.py
> +        assert self._is_unitary, "Cannot retrieve a linear circuit because some components are non-unitary"
Done

2023-07-26 09:44 UTC, ericbrts commented on perceval/components/abstract_processor.py
> +        assert self._postselect is None or processor._postselect is None, \
Done

2023-07-26 09:58 UTC, ericbrts commented on perceval/components/_mode_connector.py
>          # Handle list input case
Done

2023-07-26 10:04 UTC, MarionQuandela approved these changes

2023-07-26 11:48 UTC, merged