PCVL-657 Send NoiseModel & PostSelect in payload
Quandela/Perceval pull request #374
Opened 2024-03-05 09:42 UTC by ericbrts

2024-03-07 10:47 UTC, raksharuia commented on perceval/serialization/deserialize.py
> +        class_obj = obj[6:p+6]
I would suggest replacing the number '6' in the code, perhaps using `len(PCVL_PREFIX)` to allow for a quicker understanding.

2024-03-07 10:47 UTC, raksharuia commented on tests/test_job.py
> +from _mock_rpc_handler import MockRPCHandler, REMOTE_JOB_DURATION, REMOTE_JOB_RESULTS, REMOTE_JOB_CREATION_TIMESTAMP, \
Wondering -
Should we split this file into 2 test files? `test_job.py` and `test_remote_job.py`? I kept trying to find import statements at the top hahaha :-D :-(

2024-03-13 18:52 UTC, MarionQuandela requested changes
The worker accept the modifications without complaining (and do nothing) don't we want to add some key verification worker side ?
Some typo:
- connectible -> connectable
- distinguishible -> distinguishable

2024-03-18 15:05 UTC, ericbrts commented on perceval/components/source.py
> +            return Source()
Let's say `Source` previously was our noise data class and computation class at the same time.
Now, it's split into two classes, but of course `NoiseModel` and `Source` are going to share some parameters, as they both handle noise parameters.

2024-03-18 15:24 UTC, ericbrts commented on perceval/components/processor.py
> +        self._inputs_map = None
Historical naming - even though it's a private member, I know it's inspected from the outside sometimes, so I wouldn't like to change it.
The naming refers to:
* map: our distributions being dictionaries (or maps),
* inputs: the plural of input (it's probably improper English) to express the fact we now have several inputs to handle (that's how noisy inputs are represented).

2024-03-18 16:26 UTC, merged