Pcvl 774 promote display config to a persistent config
Quandela/Perceval pull request #471
Opened 2024-10-10 15:24 UTC by MarionQuandela

2024-10-14 12:51 UTC, raksharuia commented on perceval/rendering/circuit/display_config.py
> +    _selected_skin = _get_default_skin()
Include documentation.

2024-10-16 12:21 UTC, raksharuia requested changes

2024-10-16 12:21 UTC, raksharuia commented on perceval/rendering/circuit/display_config.py
> +    def save_select_skin() -> type:
update name to save

2024-10-16 15:24 UTC, raksharuia commented on docs/source/reference/pdisplay.rst
> +
To save configuration for your choice of skin by default, you require the `DisplayConfig` object. Usage example -

2024-10-16 15:24 UTC, raksharuia commented on perceval/rendering/circuit/display_config.py
> +        - Skin use for pdisplay. Default skin is the one in the persistent data or, if no config is find, PhysSkin.
.... if no config is fOUnd, ...

2024-10-16 15:24 UTC, raksharuia commented on perceval/rendering/circuit/display_config.py
> +        """Select the skin pdisplay uses
used by pdisplay

2024-10-16 15:46 UTC, ericbrts commented on docs/source/reference/pdisplay.rst
> +  from perceval.rendering.circuit import DisplayConfig, SymbSkin
Should we expose `DisplayConfig` and skin classes directly from `perceval.rendering` to simplify this import? (I'm for it)

2024-10-17 09:51 UTC, raksharuia approved these changes

2024-10-17 10:25 UTC, merged