Pcvl 800 1st feed forward simulator
Quandela/Perceval pull request #480
Opened 2024-11-18 16:20 UTC by Aubaert

Creation of the new feed-forward simulator.

The feed-forward map configurator class serves as an example of configurator.
This PR does not include specific interactions between Processor and FFConfigurator.
These are not the main topic of the PR and should be better implemented in another PR.[https://github.com/Quandela/Perceval/pull/481](url)

2024-11-20 17:16 UTC, raksharuia commented on tests/test_ff_simulator.py
> +
Maybe you should add a test here that keeping an offset > 1 does not cause errors in computation.

2024-11-21 10:50 UTC, ericbrts requested changes

2024-11-21 10:50 UTC, ericbrts commented on perceval/simulators/feed_forward_simulator.py
> +                    proc.add_herald(r, v)
This call adds heralds on both the input and output of `proc`. I think you want to fix heralds only in the output, which can be achieved with :

```python
proc.add_port(r, Herald(v), PortLocation.OUTPUT)
```

2024-11-21 10:50 UTC, ericbrts commented on perceval/simulators/feed_forward_simulator.py
> +                    sub_res = sim.probs_svd(input_state, detectors, new_prog_cb, normalize=False)["results"]
When the FF configurator injects a `Processor` with heralds, the `input_state` here needs to be adjusted to take the modes covered by heralds into account.

2024-11-22 15:06 UTC, Aubaert commented on perceval/simulators/feed_forward_simulator.py
> +    def _probs_or_svd(self,
It was changed to `_probs_svd`, and both `probs` and `probs_svd` use it with a SVD now

2024-11-26 13:58 UTC, merged