Pcvl 599 launch a job group run methods
Quandela/Perceval pull request #489
Opened 2024-12-05 12:59 UTC by raksharuia

2024-12-05 13:14 UTC, Aubaert requested changes

2024-12-05 13:14 UTC, Aubaert commented on perceval/runtime/job_group.py
> +                print('RE launching jobs in parallel')
Remove this print statement

2024-12-05 13:14 UTC, Aubaert commented on perceval/runtime/job_group.py
> +    def _launch_jobs_parallel(self, rerun: bool):
This function can be merged with the sequential launch with just a parameter that indicates that it should wait for the job to be complete.

2024-12-05 13:16 UTC, raksharuia commented on perceval/runtime/job_group.py
> +                print('RE launching jobs in parallel')
oops

2024-12-05 15:05 UTC, Aubaert approved these changes
Ok for me now

2024-12-06 14:05 UTC, Aubaert commented
Found bugs in tqdm progress bar:
- you are counting jobs at each iteration even if they already participated to the count making the count overpass the maximum of the bar
- the total for each bar is the number of jobs in the job group but it would be more logical if it was only the number of jobs that could be in that category (for example if a job is already successful for example if it was loaded from the disk before launching the tqdm progress, it is added to the total of all bars but it should only be added to the total of the success bar)

2024-12-10 11:19 UTC, merged